# Generated by Django 3.0.3 on 2020-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.IntegerField(blank=True, max_length=500, null=True)),
                ('dead', models.IntegerField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'covids',
            },
        ),
        migrations.CreateModel(
            name='KoreaCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.CharField(blank=True, max_length=250, null=True)),
                ('increase', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'korea_covids',
            },
        ),
    ]
