# Generated by Django 3.0.3 on 2020-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreacovid',
            name='patient',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
